# Chocolatey uninstall script for codetracer-cairo-recorder.
#
# Generated by codetracer-launcher/packaging/recorder-templates/generate.py
# from codetracer-cairo-recorder/packaging/recorder-metadata.yml.
# DO NOT edit this file by hand — re-run the generator instead.
#
# Chocolatey removes the contents of $toolsDir automatically as part
# of the uninstall handshake (it tracks every file it shimmed and
# unshims them). This script exists for symmetry and to give us a
# hook if codetracer-cairo-recorder ever needs explicit cleanup (registry
# entries, services, scheduled tasks, etc.). For now the only thing
# left to do is verify the zip-extract directory is gone.

$ErrorActionPreference = 'Stop'

$packageName = 'codetracer-cairo-recorder'
$toolsDir    = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"
$extractDir  = Join-Path $toolsDir 'codetracer-cairo-recorder-0.1.0-windows-x86_64'

if (Test-Path $extractDir) {
  Remove-Item -Recurse -Force $extractDir
}
